name: CraftContext
main: br.ufes.inf.lprm.bukkit.Server
version: 12.10.1
description: >
    A tool, based on Minecraft, for helping context aware applications tests. Make possible to use the Minecraft game to simulate a context source.
commands:
    player:
        description: Requests services to change or consult values about the current player. In order to use this command, you need to specify the type of the command (set_health or set_food);
        usage: /player [command_type] [parameters]
    building:
        description: Requests services to build, destroy or consult values about the constructed buildings. In order to use this command, you need to specify the type of the command (add, remove or list);
        usage: /building [command_type] [parameters]
