GEN_PATH=	..
FLAGS=		-fall

all:		idl clean
		
idl:		
#		idlj -td $(GEN_PATH) $(FLAGS) common.idl
#		idlj -td $(GEN_PATH) $(FLAGS) player.idl
		idlj -td $(GEN_PATH) $(FLAGS) building.idl
# 		idlj -td $(GEN_PATH) $(FLAGS) door.idl
# 		idlj $(GEN_PATH) $(FLAGS) chest.idl

clean:
		rm -f *~
